name: EconX
version: ${project.version}
main: com.erinnyen.econx.EconX
api-version: 1.16
authors: [ Erinnyen ]
description: A simple economics Plugin for paperserver.
website: https://github.com/Erinnyen

commands:
  send:
    description: send money between players
    usage: /<send> <player> <amount> <comment>

  getcredit:
    aliases: [credit]
    description: get your own credit
    usage: /<getcredit>


  recent:
    aliases: [recenttransactions, getrecent]
    description: view the recent transactions associated with your account
    usage: /<recent>

  sell:
    description: Use this to sell items.
    usage: /<sell> <asked-price>

  getSellOrders:
    description: Kind of like the recent command, just for the open sellorders.
    usage: /<sellorders>