name: EconX
version: 1.0-SNAPSHOT
main: com.erinnyen.econx.EconX
api-version: 1.16
authors: [ Erinnyen ]
description: A simple economics Plugin for paperserver.
website: https://github.com/Erinnyen

commands:
  send:
    description: send money between players

  getcredit:
    aliases: [credit]
    description: get your own credit


  recent:
    aliases: [recenttransactions, getrecent]
    description: view the recent transactions associated with your account